### ISSUE TITLE
Scale down input image so 1 px = 1 crewmate

### ISSUE THREAD

**Issue by makeworld-the-better-one** [LinesGuy/img_sussifier#1]
If the input image is scaled down so each pixel corresponds to a crewmate before the loop, the colors of each crewmate are way more accurate.

Compare (width is 30):

Original:

![wtf](https://user-images.githubusercontent.com/25111343/120125749-ffb91f00-c187-11eb-9f76-c453d8e24419.GIF)

Before patch:

![wtf](https://user-images.githubusercontent.com/25111343/120125758-08115a00-c188-11eb-9c9b-6f6a232000a3.gif)

You can see how it picks up the noise in the image and uses the colors poorly

After patch:

![sussified](https://user-images.githubusercontent.com/25111343/120125791-1790a300-c188-11eb-8e08-b039c2c8f263.gif)

The patch can be viewed here: https://github.com/makeworld-the-better-one/img_sussifier/commit/5eb29c4235238f59fa2e19b5ec4216a37cc7368f

My fork targets Linux and has likely diverged too much to make a PR useful, but you can just change that bit of code to gain this feature.

**Comment by LinesGuy** [comment]
The code used to do this but I ultimately changed it as it would mess up flags, which was what I originally made the program for

For example (width is 30)
Before patch:
![nearest_neighbour.gif](https://user-images.githubusercontent.com/60029482/120168072-6117d700-c1f6-11eb-84d1-6b13a16c4213.gif)
After patch:
![no_nearest_neighbour.gif](https://user-images.githubusercontent.com/60029482/120168077-637a3100-c1f6-11eb-95cb-305040a2be76.gif)

In any case, I'll add your code in and add an option for whether to use normal scaling or nearest-neighbour scaling. Thanks

**Comment by makeworld-the-better-one** [comment]
Hmm yeah I see the issue, I guess this would apply to most "vector art" style images that also have blurred/anti-aliased edges. But you just got lucky with that image, like that there weren't any blurred edges over the pixels that are picked up. It could easily look bad as well.

I tried to use nearest-neighbor scaling instead of the default, and these were the results:

![british_flag](https://user-images.githubusercontent.com/25111343/120202584-c23eab00-c1f4-11eb-8d59-08e691adff14.gif)

![sussified](https://user-images.githubusercontent.com/25111343/120202595-c66ac880-c1f4-11eb-8d29-1d8968bb6d40.gif)

Works well for vector art, but not for noisy images. I'll add an option like you did in https://github.com/LinesGuy/img_sussifier/commit/4321717fb9227cec4f15965330716be9cb5a94cc, makes sense.
