### ISSUE TITLE
"Inspiration"

### ISSUE THREAD

**Issue by ThatOneCalculator** [LinesGuy/img_sussifier#5]
This is clearly just a recreation of my program: https://github.com/ThatOneCalculator/Among-Us-Dumpy-Gif-Maker

While that's fine on its own, you gave ABSOLUTELY NO CREDIT. Given your program does exactly the same thing as mine, going as far as to use the same assets, credit would be appreciated.

**Comment by LinesGuy** [comment]
sup

i didn't copy jack

I saw a gif on the information superhighway and wanted to make a script that can make similar gifs, I got the assets by cropping an existing gif.

in any case, your program evidently has more effort put into it, so I'll link it at the top of my README anyway

cheers lad

**Comment by adryzz** [comment]
chad

**Comment by ThatOneCalculator** [comment]
Mostly chad; but "didnt copy jack" isnt entirely true, given the program emulates mine and still uses the same assets. I thank you @LinesGuy for adding the credit, but there was def copying. Not that it's a bad thing per say. Thank you again for adding the credit.
